version: '3'

services:
  api:
    build: .
    labels:
      - "traefik.frontend.rule=Host:overwatch-api.docker.localhost"
      - "traefik.port=3000"
    command: "npm run docs"

  reverse-proxy:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock